spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mariadb://localhost:3306/test_pubsub
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
